### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by t-8ch**
Some more fixes.
Should it make any problems for the network if I create supernodes for testing?

Also I don't know how the `/etc/fw/` stuff is supposed to work

### CODE REVIEW

**Comment by christf** [comment]
On Saturday 03 October 2015 01:40:57 Thomas Weißschuh wrote:

> Some more fixes.
> Should it make any problems for the network if I create supernodes for
> testing?
> As long as you deactivate dhcp you should not impact network
> performance.
> 
> Also I don't know how the `/etc/fw/` stuff is supposed to work
> The directory is a paceholder. The puppet script should fail if there is
> no firewall-script to enforce proper firewalling. The firewalls are
> generated by fwbuilder which is more flexible than using custom scripts
> and deploying them via puppet. 
> 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/freifunk-ffm/supernode_puppet/pull/3
> 
> -- Commit Summary --
> - remove use of exec
> - remve another use of exec
> - use the proper datatype
> - fix postfix
> - remove dependency cycle
> 
> -- File Changes --
> 
> ```
> M modules/batman/manifests/init.pp (17)
> M modules/fastd/manifests/init.pp (10)
> M modules/ffmff/manifests/apt.pp (2)
> M modules/firewall/manifests/init.pp (2)
> M modules/postfix/manifests/init.pp (7)
> ```
> 
> -- Patch Links --
> 
> https://github.com/freifunk-ffm/supernode_puppet/pull/3.patch
> https://github.com/freifunk-ffm/supernode_puppet/pull/3.diff
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/freifunk-ffm/supernode_puppet/pull/3

## 

()  ascii ribbon campaign - against html e-mail
/\  against proprietary attachments

**Comment by t-8ch** [comment]
Care to test again?
I accidentally enabled dhcp because the fastd post-up script started the service.
Are all supernodes on jessie? Then we could use systemds `systemctl try-restart` which only restart running services.

**Comment by christf** [comment]
not all of the supernodes are running jessie yet. this is on the todo list.
Also batmanv14 needs a patch to compile for kernels >4.1
I wonder if it is the right thing to apply it here or in batman-advanced-dkms...

**Comment by t-8ch** [comment]
OK, the current code uses systemd templated units for fastd and openvpn. I will rework this and test it on wheezy.

On October 4, 2015 3:58:47 PM GMT+02:00, Christof Schulze notifications@github.com wrote:

> not all of the supernodes are running jessie yet. this is on the todo
> list.
> Also batmanv14 needs a patch to compile for kernels >4.1
> I wonder if it is the right thing to apply it here or in
> batman-advanced-dkms...
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/freifunk-ffm/supernode_puppet/pull/3#issuecomment-145351866

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by christf** [comment]
On Sunday 04 October 2015 07:09:12 Thomas Weißschuh wrote:

> OK, the current code uses systemd templated units for fastd and openvpn. I
> will rework this and test it on wheezy.
> On October 4, 2015 3:58:47 PM GMT+02:00, Christof Schulze 
> notifications@github.com wrote:
> 
> > not all of the supernodes are running jessie yet. this is on the todo
> > list.
> > Also batmanv14 needs a patch to compile for kernels >4.1
> > I wonder if it is the right thing to apply it here or in
> > batman-advanced-dkms...
> > I am planning to run the upgrade within the next week. running an
> > oldstable for long really is not an option.

## 

()  ascii ribbon campaign - against html e-mail
/\  against proprietary attachments

**Pull request merged**
